# Generated by Django 5.2.17 on 2026-09-18 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aa_altcorp', '0003_standing_target_eve_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Has the ability to view this page'), ('manage_relationships', 'Has the ability to add relationships'), ('view_alerts', 'Has the ability to view contact and ACL alerts'), ('manage_alerts', 'Has the ability to manage alert exemptions and ACL policies')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AccessListPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_list_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('expect_positive_contacts', models.BooleanField(default=True, help_text='Every blue contact is expected to have access to this ACL')),
                ('minimum_standing', models.FloatField(default=0.1, help_text='Standing floor used by expect_positive_contacts')),
                ('expect_states', models.JSONField(blank=True, default=list, help_text='Alliance Auth state names expected to have access')),
                ('expect_groups', models.JSONField(blank=True, default=list, help_text='Alliance Auth group names expected to have access')),
                ('expect_corporations', models.JSONField(blank=True, default=list, help_text='EVE corporation IDs expected to have access')),
                ('expect_alliances', models.JSONField(blank=True, default=list, help_text='EVE alliance IDs expected to have access')),
                ('expect_entities', models.JSONField(blank=True, default=list, help_text='Explicit entries, each with entity_type, entity_id and an optional name')),
                ('expect_mains_only', models.BooleanField(default=False, help_text='Restrict state and group rules to main characters')),
                ('expected_tier', models.CharField(choices=[('character', 'Character'), ('corporation', 'Corporation'), ('alliance', 'Alliance')], default='character', help_text='Tier that corporation and alliance rules expand to', max_length=12)),
                ('alert_missing', models.BooleanField(default=True, help_text='Alert when an expected entity is absent from this ACL')),
                ('alert_unexpected', models.BooleanField(default=True, help_text='Alert when an unexpected entity has access to this ACL')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Access list policy',
                'verbose_name_plural': 'Access list policies',
                'ordering': ('name', 'access_list_id'),
            },
        ),
        migrations.AlterModelOptions(
            name='altcorpsettings',
            options={'verbose_name': 'Alt Corp settings'},
        ),
        migrations.AddField(
            model_name='altcorpsettings',
            name='alert_batch_size',
            field=models.PositiveSmallIntegerField(default=10, help_text='Alerts delivered per batch, to stay inside Discord rate limits'),
        ),
        migrations.AddField(
            model_name='altcorpsettings',
            name='alert_delivery',
            field=models.CharField(choices=[('auto', 'Automatic (bot when available, otherwise webhook)'), ('bot', 'Discord bot only'), ('webhook', 'Webhook only'), ('none', 'Do not deliver')], default='auto', max_length=8),
        ),
        migrations.AddField(
            model_name='altcorpsettings',
            name='alerts_enabled',
            field=models.BooleanField(default=False, help_text='Off by default so upgrading does not start alerting unannounced'),
        ),
        migrations.AddField(
            model_name='altcorpsettings',
            name='discord_channel_id',
            field=models.BigIntegerField(blank=True, help_text='Channel the alert engine posts to via the bot', null=True),
        ),
        migrations.AddField(
            model_name='altcorpsettings',
            name='discord_guild_id',
            field=models.BigIntegerField(blank=True, help_text='Guild the alert channel lives in, used for logging', null=True),
        ),
        migrations.AddField(
            model_name='altcorpsettings',
            name='discord_role_ids',
            field=models.JSONField(blank=True, default=list, help_text='Discord role IDs allowed to action alerts. Holding one of these grants Auth-side exemption powers without any Django permission.'),
        ),
        migrations.AddField(
            model_name='altcorpsettings',
            name='expect_all_owned_characters',
            field=models.BooleanField(default=False, help_text='Off: only main characters and explicitly attached alts are expected to hold standing. On: every owned character of a valid-state user is.'),
        ),
        migrations.AddField(
            model_name='altcorpsettings',
            name='expect_contact_alliances',
            field=models.BooleanField(default=False, help_text='Alliance-level blue is usually a deliberate diplomatic act, not a per-member consequence'),
        ),
        migrations.AddField(
            model_name='altcorpsettings',
            name='expect_contact_characters',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='altcorpsettings',
            name='expect_contact_corporations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='altcorpsettings',
            name='minimum_blue_standing',
            field=models.FloatField(default=0.1, help_text='Standing at or above which a contact counts as blue'),
        ),
        migrations.AddField(
            model_name='altcorpsettings',
            name='renotify_interval_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Re-deliver still-open alerts after this many days; 0 notifies once'),
        ),
        migrations.AddField(
            model_name='altcorpsettings',
            name='treat_zero_standing_as_removed',
            field=models.BooleanField(default=True, help_text='aa-contacts forces standing to 0.0 instead of deleting contacts that carry notes or server links, so 0.0 is ambiguous. Enabled means 0.0 counts as no standing.'),
        ),
        migrations.AlterField(
            model_name='altcorpsettings',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='Fallback delivery. Webhooks cannot carry buttons; the bot is needed for those.'),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('missing_for_valid_user', 'Missing for valid user'), ('present_for_invalid_user', 'Present for invalid user'), ('present_without_auth_user', 'Present without Auth user')], max_length=32)),
                ('entity_type', models.CharField(choices=[('character', 'Character'), ('corporation', 'Corporation'), ('alliance', 'Alliance')], max_length=12)),
                ('entity_id', models.BigIntegerField()),
                ('entity_name', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=12)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('dedup_key', models.CharField(editable=False, max_length=190, unique=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('scan_id', models.UUIDField(blank=True, null=True)),
                ('discord_channel_id', models.BigIntegerField(blank=True, null=True)),
                ('discord_message_id', models.BigIntegerField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('delivery', models.CharField(blank=True, choices=[('bot', 'Discord bot'), ('webhook', 'Webhook')], max_length=12)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='altcorp_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_seen_at',),
            },
        ),
        migrations.CreateModel(
            name='Exemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mark_exempt', 'Mark exempt'), ('temporary_blue', 'Temporary blue'), ('temporary_acl_exemption', 'Temporary ACL exemption')], max_length=24)),
                ('direction', models.CharField(choices=[('missing', 'Missing'), ('present', 'Present')], max_length=8)),
                ('facet_type', models.CharField(choices=[('contact', 'Contact standing'), ('acl', 'Access list')], max_length=8)),
                ('entity_type', models.CharField(choices=[('character', 'Character'), ('corporation', 'Corporation'), ('alliance', 'Alliance')], max_length=12)),
                ('entity_id', models.BigIntegerField()),
                ('entity_name', models.CharField(blank=True, max_length=255)),
                ('access_list_id', models.BigIntegerField(blank=True, null=True)),
                ('access_list_name', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(help_text='Required. Explains the decision to whoever reads it later')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Empty means the exemption never expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_discord_id', models.BigIntegerField(blank=True, null=True)),
                ('created_by_discord_name', models.CharField(blank=True, max_length=190)),
                ('created_by_guild_id', models.BigIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('discord', 'Discord'), ('admin', 'Django admin')], default='discord', max_length=12)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_by_discord_id', models.BigIntegerField(blank=True, null=True)),
                ('revoked_reason', models.TextField(blank=True)),
                ('match_key', models.CharField(db_index=True, editable=False, max_length=190)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='aa_altcorp.alert')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AlertFacet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facet_type', models.CharField(choices=[('contact', 'Contact standing'), ('acl', 'Access list')], max_length=8)),
                ('access_list_id', models.BigIntegerField(blank=True, null=True)),
                ('access_list_name', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(choices=[('open', 'Open'), ('suppressed', 'Suppressed'), ('resolved', 'Resolved')], default='open', max_length=12)),
                ('reason_text', models.CharField(blank=True, max_length=500)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facets', to='aa_altcorp.alert')),
                ('suppressed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppressed_facets', to='aa_altcorp.exemption')),
            ],
            options={
                'ordering': ('facet_type', 'access_list_name', 'access_list_id'),
            },
        ),
        migrations.CreateModel(
            name='AlertActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('MARK_EXEMPT', 'Mark exempt'), ('TEMPORARY_BLUE', 'Temporary blue'), ('TEMPORARY_ACL_EXEMPTION', 'Temporary ACL exemption'), ('REMOVE_EXEMPTION', 'Remove exemption')], max_length=32)),
                ('alert_type', models.CharField(blank=True, max_length=32)),
                ('entity_type', models.CharField(max_length=12)),
                ('entity_id', models.BigIntegerField()),
                ('entity_name', models.CharField(blank=True, max_length=255)),
                ('facets_affected', models.JSONField(blank=True, default=list, help_text='Snapshot of the facets this action covered')),
                ('reason', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('actor_discord_id', models.BigIntegerField(blank=True, null=True)),
                ('actor_discord_name', models.CharField(blank=True, max_length=190)),
                ('actor_guild_id', models.BigIntegerField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='aa_altcorp.alert')),
                ('exemptions', models.ManyToManyField(blank=True, related_name='action_logs', to='aa_altcorp.exemption')),
            ],
            options={
                'verbose_name': 'Alert action log',
                'verbose_name_plural': 'Alert action log',
                'ordering': ('-performed_at',),
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['state', 'alert_type'], name='altcorp_alert_state_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['entity_type', 'entity_id'], name='altcorp_alert_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['state', 'notified_at'], name='altcorp_alert_notify_idx'),
        ),
        migrations.AddIndex(
            model_name='exemption',
            index=models.Index(fields=['match_key', 'revoked_at'], name='altcorp_exempt_match_idx'),
        ),
        migrations.AddIndex(
            model_name='exemption',
            index=models.Index(fields=['kind', 'expires_at'], name='altcorp_exempt_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='exemption',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('access_list_id__isnull', False), ('facet_type', 'acl')), models.Q(('facet_type', 'acl'), _negated=True), _connector='OR'), name='altcorp_acl_exemption_needs_acl'),
        ),
        migrations.AddConstraint(
            model_name='alertfacet',
            constraint=models.UniqueConstraint(fields=('alert', 'facet_type', 'access_list_id'), name='altcorp_unique_alert_facet'),
        ),
    ]
